import { IData } from './types'
export const allBetDummy: IData[] = [
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '让球',
        betDateTime: '2021-02-01 23:30:30',
        gameTypeName: '1x100.00',
        processed: false,
        gameCode: null,
        betAmount: 100,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18406,
            uuId: 'ZQ210201673702006',
            ante: 100,
            totalAnte: 100,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 4038.03,
            label: '让球',
            betDt: '2021-02-01 23:30:30.0',
            lastKickOffDt: '2021-02-02 14:00:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'mobile',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18581,
                    sId: 1,
                    kId: 4632054,
                    mId: 4632054,
                    leagueId: 26726,
                    league: '英格兰超级联赛',
                    ctid: 0,
                    homeTeam: '狼队',
                    awayTeam: '阿森纳',
                    currMatchTime: null,
                    homeScore: 0,
                    awayScore: 0,
                    n1: 0,
                    n2: 0.5,
                    odds1: 1.02,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-02-01 23:30:30.0',
                    sType: 'ah',
                    betDetail: 'h',
                    isMatchCancelled: 0,
                    betFormTitle: '让球',
                    betFormDetail: '狼队',
                    betFormH: '+0/0.5',
                    isLive: false,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: 1.02,
                    aOdds: 0.91,
                    dOdds: null,
                    latestOdds: null,
                    lastKickOffDt: '2021-02-02 14:00:00.0',
                    betDt: '2021-02-01 23:30:30.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: false,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-02-02 14:00:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 102,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -100,
        },
        betRecordId: 'ZQ210201673702006',
    },
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '独赢',
        betDateTime: '2021-02-01 23:29:54',
        gameTypeName: '1x100.00',
        processed: false,
        gameCode: null,
        betAmount: 100,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18405,
            uuId: 'ZQ210201815372756',
            ante: 100,
            totalAnte: 100,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 4138.03,
            label: '独赢',
            betDt: '2021-02-01 23:29:54.0',
            lastKickOffDt: '2021-02-02 08:30:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'desktop',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18580,
                    sId: 1,
                    kId: 4641813,
                    mId: 4641813,
                    leagueId: 26146,
                    league: '埃及超级联赛',
                    ctid: 0,
                    homeTeam: '阿斯罔',
                    awayTeam: '切拉米卡克里奥帕特拉',
                    currMatchTime: null,
                    homeScore: 0,
                    awayScore: 0,
                    n1: 0,
                    n2: 0,
                    odds1: 3.5,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-02-01 23:29:54.0',
                    sType: 'had',
                    betDetail: 'h',
                    isMatchCancelled: 0,
                    betFormTitle: '独赢',
                    betFormDetail: '阿斯罔',
                    betFormH: '',
                    isLive: false,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: 3.5,
                    aOdds: 2.12,
                    dOdds: 2.9,
                    latestOdds: null,
                    lastKickOffDt: '2021-02-02 08:30:00.0',
                    betDt: '2021-02-01 23:29:54.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: true,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-02-02 08:30:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 250,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -100,
        },
        betRecordId: 'ZQ210201815372756',
    },
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '进球 :滚球 大 / 小',
        betDateTime: '2021-01-31 23:42:35',
        gameTypeName: '1x11.00',
        processed: false,
        gameCode: null,
        betAmount: 11,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18379,
            uuId: 'ZQ210131876872872',
            ante: 11,
            totalAnte: 11,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 0,
            label: '进球 :滚球 大 / 小',
            betDt: '2021-01-31 23:42:35.0',
            lastKickOffDt: '2021-01-31 23:38:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'desktop',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18551,
                    sId: 1,
                    kId: 4657663,
                    mId: 4657663,
                    leagueId: 103551,
                    league: '电竞足球-FIFA 21 CLA意大利杯-10分钟比赛',
                    ctid: 0,
                    homeTeam: 'Atalanta (ViTo) Esports',
                    awayTeam: 'AC Milan (Member) Esports',
                    currMatchTime: '03:39',
                    homeScore: 0,
                    awayScore: 0,
                    n1: 2.5,
                    n2: 3,
                    odds1: 0.7,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-01-31 23:42:35.0',
                    sType: 'ou',
                    betDetail: 'ov',
                    isMatchCancelled: 0,
                    betFormTitle: '进球 :滚球 大 / 小',
                    betFormDetail: '大',
                    betFormH: '2.5/3',
                    isLive: true,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: 0.7,
                    aOdds: 1,
                    dOdds: null,
                    latestOdds: null,
                    lastKickOffDt: '2021-01-31 23:38:00.0',
                    betDt: '2021-01-31 23:42:35.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: false,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-01-31 23:38:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 7.7,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -11,
        },
        betRecordId: 'ZQ210131876872872',
    },
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '让球',
        betDateTime: '2021-01-31 22:56:39',
        gameTypeName: '1x11.00',
        processed: false,
        gameCode: null,
        betAmount: 11,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18374,
            uuId: 'LQ210131000641613',
            ante: 11,
            totalAnte: 11,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 0,
            label: '让球',
            betDt: '2021-01-31 22:56:39.0',
            lastKickOffDt: '2021-02-01 07:35:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'desktop',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18546,
                    sId: 2,
                    kId: 4647514,
                    mId: 4647514,
                    leagueId: 101288,
                    league: '中国男子篮球职业联赛(在浙江)',
                    ctid: 0,
                    homeTeam: '浙江广厦猛狮',
                    awayTeam: '山东王者',
                    currMatchTime: '',
                    homeScore: 0,
                    awayScore: 0,
                    n1: -1.5,
                    n2: -1.5,
                    odds1: 1.05,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-01-31 22:56:39.0',
                    sType: 'ah',
                    betDetail: 'a',
                    isMatchCancelled: 0,
                    betFormTitle: '让球',
                    betFormDetail: '山东王者',
                    betFormH: '+1.5',
                    isLive: false,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: 0.75,
                    aOdds: 1.05,
                    dOdds: null,
                    latestOdds: null,
                    lastKickOffDt: '2021-02-01 07:35:00.0',
                    betDt: '2021-01-31 22:56:39.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: false,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-02-01 07:35:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 11.55,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -11,
        },
        betRecordId: 'LQ210131000641613',
    },
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '滚球 让球',
        betDateTime: '2021-01-31 21:54:58',
        gameTypeName: '1x111.00',
        processed: false,
        gameCode: null,
        betAmount: 111,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18371,
            uuId: 'ZQ210131083713469',
            ante: 111,
            totalAnte: 111,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 0,
            label: '滚球 让球',
            betDt: '2021-01-31 21:54:58.0',
            lastKickOffDt: '2021-01-31 20:24:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'desktop',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18543,
                    sId: 1,
                    kId: 4644957,
                    mId: 4644957,
                    leagueId: 26393,
                    league: '国际友谊赛',
                    ctid: 0,
                    homeTeam: '美国',
                    awayTeam: '千里达及多巴哥',
                    currMatchTime: '72:25',
                    homeScore: 7,
                    awayScore: 0,
                    n1: -0.5,
                    n2: -0.5,
                    odds1: 0.91,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-01-31 21:54:58.0',
                    sType: 'ah',
                    betDetail: 'h',
                    isMatchCancelled: 0,
                    betFormTitle: '滚球 让球',
                    betFormDetail: '美国',
                    betFormH: '-0.5',
                    isLive: true,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: 0.91,
                    aOdds: 1.01,
                    dOdds: null,
                    latestOdds: null,
                    lastKickOffDt: '2021-01-31 20:24:00.0',
                    betDt: '2021-01-31 21:54:58.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: false,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-01-31 20:24:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 101.01,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -111,
        },
        betRecordId: 'ZQ210131083713469',
    },
    {
        username: 'abcd123',
        cancelled: false,
        gameSupplier: 'sportV1',
        gamePlayName: '更高赔率',
        betDateTime: '2021-01-28 02:58:43',
        gameTypeName: '1x10.00',
        processed: false,
        gameCode: null,
        betAmount: 10,
        payoutAmount: 0,
        netProfit: 0,
        validBetAmount: 0,
        gameDetail: {
            masterId: 18357,
            uuId: 'ZQ210128943795245',
            ante: 10,
            totalAnte: 10,
            effectiveTotalAnte: 0,
            processed: 0,
            paid: 0,
            payout: 0,
            balanceAfterBet: 4468.67,
            label: '更高赔率',
            betDt: '2021-01-28 02:58:43.0',
            lastKickOffDt: '2021-01-29 16:00:00.0',
            payoutDt: null,
            matchCount: 1,
            mCount: 1,
            cCount: 1,
            unitCount: 1,
            platform: 'mobile',
            odds1: null,
            odds2: null,
            betSportDetails: [],
            betSportOrDetails: [],
            betSportDetailEntities: [
                {
                    rowId: 18529,
                    sId: 1,
                    kId: 4625669,
                    mId: 4625669,
                    leagueId: 27068,
                    league: '西班牙甲组联赛',
                    ctid: 0,
                    homeTeam: '巴拉多利德',
                    awayTeam: '韦斯卡',
                    currMatchTime: null,
                    homeScore: 0,
                    awayScore: 0,
                    n1: 0,
                    n2: 0,
                    odds1: 31,
                    odds2: 0,
                    isEnded: 0,
                    isCancel: 0,
                    cancelDt: '2021-01-28 02:58:43.0',
                    sType: 'eps',
                    betDetail: 'o5726228823',
                    isMatchCancelled: 0,
                    betFormTitle: '更高赔率',
                    betFormDetail: '巴拉多利德会赢3-0',
                    betFormH: '',
                    isLive: false,
                    cancelReason: null,
                    matchScore: null,
                    hOdds: null,
                    aOdds: null,
                    dOdds: null,
                    latestOdds: null,
                    lastKickOffDt: '2021-01-29 16:00:00.0',
                    betDt: '2021-01-28 02:58:43.0',
                    payoutDt: null,
                    isEarlySettled: false,
                    earlySettleDt: null,
                    allowEarlySettle: false,
                    matchDt: null,
                    liveTime: null,
                    currSet: null,
                    hDetail: null,
                    aDetail: null,
                    dDetail: null,
                    spType: null,
                    id: null,
                    pt: 0,
                    h: null,
                    a: null,
                    singleBetAmount: null,
                    ename: null,
                    oddsResult: null,
                    kickOffTimestamp: 0,
                    marketId: null,
                    outcomeId: null,
                    spDetail: null,
                    kickOffDt: '2021-01-29 16:00:00.0',
                    winLoseStatus: null,
                    fantasy: false,
                    cancelled: false,
                },
            ],
            betSportOrDetailEntities: [],
            normalSettleTbc: false,
            estimatedWinnings: 300,
            stype: null,
            sid: 0,
            stype2: null,
            draw: false,
            containWorldCup: false,
            noProfit: false,
            oddsListFromDetails: [],
            live: false,
            profit: -10,
        },
        betRecordId: 'ZQ210128943795245',
    },
]
export const allSportsSettledBetDummy: IData[] = []
export const sportsUnsettledDummy: IData[] = []
export const bgagBetDummy: IData[] = []
export const mgBetDummy: IData[] = []
export const dtkynnBetDummy: IData[] = []
export const allLotteryBetDummy: IData[] = []
export const lotterySettledBetDummy: IData[] = []
export const lotteryUnsettledBetDummy: IData[] = []
